source "https://rubygems.org"

# Sass, Compass and extensions.
gem 'sass'
gem 'sass-globbing'
gem 'compass'
gem 'susy'
gem 'breakpoint'

# Dependency to prevent polling. Setup for multiple OS environments.
# Optionally remove the lines not specific to your OS.
# https://github.com/guard/guard#efficient-filesystem-handling
gem 'rb-inotify', '~> 0.9', :require => false      # Linux
gem 'rb-fsevent', :require => false                # Mac OSX
gem 'rb-fchange', :require => false                # Windows
