name = Off Layout
description = Implementación propia de off canvas.
preview = img/preview.png
template = off-layout

; Regions
regions[heading]        = Heading
regions[branding]       = Branding
regions[header]         = Header
regions[navigation]     = Navigation
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[pre_content]    = Pre Content
regions[content]        = Content
regions[post_content]   = Post Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[post_footer]    = Post Footer

; Stylesheets
stylesheets[all][] = css/off-layout.css

; Scripts
scripts[] = js/off-layout.js
