name = Landing
description = Tipo portada landing asi to buena
preview = preview.png
template = landing-layout

; Regions
regions[one]    = One
regions[two]    = Two
regions[three]  = Three
regions[four]   = Four
regions[five]   = Five
regions[six]    = Six
regions[seven]  = Seven
regions[eight]  = Eight
regions[nine]   = Nine
regions[ten]    = Ten

; Stylesheets
stylesheets[all][] = css/landing.layout.css

; Scripts
;scripts[] = js/off-layout.js