<?php

/**
 * Implements hook_menu().
 */
function session_schedule_menu() {
  // @todo la url es temporal.
  $items['sesiones'] = array(
    'title' => 'Session schedule',
    'page callback' => 'render_session_schedule',
    'access arguments' => array(TRUE),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementa hook_theme().
 */
function session_schedule_theme() {
  return array(
    'session_schedule' => array(
      'variables' => array(),
      'template' => 'session-schedule',
    )
  );
}

function render_session_schedule() {
  drupal_add_css(drupal_get_path('module', 'session_schedule') . '/session-schedule.css');
  return theme('session_schedule');
}